### PR TITLE
Sync Quest Files

### PR DESCRIPTION
**Pull request by Cerexus**
PikaMug#312

I´ll start helping to sync the Data of the Quest Files. Please take a look at it if you would accept that way.

It is the simplest way to do that.

### CODE REVIEW

**Comment by Cerexus** [comment]
ToDo:
- push Updates when changes are made to one of these files via the editor
- command to manually push it when changes are made to the file directly
- pullig the files with the existing plugin reload
- pulling the files at server startup

If you would accept that, id need your help to add the methods at the right place. im not sure at which places changes are made through the editor

**Comment by PikaMug** [comment]
Thanks for the PR. Supporting quests/actions/conditions via MySQL is something that would benefit the project, but is of low urgency at this time. There are a few changes I would like to the YAML implementation first, and QuestsConverter would need to be updated for both that and your submission. I'll leave this open should you like to finish the work for consideration at a later date, but that would be several weeks away at best.

**Comment by Cerexus** [comment]
The big advantage is that any changes to yaml are irrelevant, because the file is saved in mysql as it is. So you can change everything with yml and it does not matter.

For our network it is important to have this feature :D We just waited over a year that someone is adding multiserver support (also other quest plugins). but no one got an working version. we will stay at quests bc it is better than all the other quest plugins.

i will definetly finish this, but i need your help with adding the methods everywhere where changes are made to this files.

**Comment by Cerexus** [comment]
I dont know if i did the merge in the right way ._.  Was the first time.
Im sorry if it was wrong

**Comment by PikaMug** [comment]
@Cerexus The plugin is now ready to undertake syncing of quests. Due to changes made, you may wish to close this PR and create a new one to avoid conflict resolution. I'll leave this open pending your decision.

**Comment by PikaMug** [comment]
Closing due to unresolved conflicts.

**Pull request closed without merging**
