### PR TITLE
Additional custom objective methods

### PR DESCRIPTION
**Pull request by MrGraycat**
I was making myself a custom objective and wanted to use more customized displays/quest progress since I'm tracking multiple mobs at once. 
I'm aware I'm using the custom objective outside their designed boundaries but it does the trick and will keep working with the old methods and maybe some other people are able to find a use for it as well.

Let me know if there are any further issues/questions.
Graycat

### CODE REVIEW

**Comment by PikaMug** [comment]
Thanks for the submission.

What is the purpose of this? It seems there is just a second display variable now?

**Comment by MrGraycat** [comment]
Well I use this for my custom objective the getDisplay with arguments is so I can get the proper set values from the objective to set the display properly as getData() returned the default ones. Then I also added the FinishDisplay to set a summary message instead of the full list of all mobs. Basically because my module keeps track of multiple entities at once making me have to 'get creative' as mentioned by the mods in the Discord.

Graycat

**Comment by PikaMug** [comment]
`#getData` will return default values but you should be able to work with `#getDataForPlayer`? Sorry, but even with multiple entities I'm not seeing why this is needed. Perhaps some example code would help clarify?

Thank you for finding that NPE, it was just resolved in #2182

**Comment by MrGraycat** [comment]
> `#getData` will return default values but you should be able to work with `#getDataForPlayer`? Sorry, but even with multiple entities I'm not seeing why this is needed. Perhaps some example code would help clarify?
> 
> Thank you for finding that NPE, it was just resolved in #2182

I'm using getDataForPlayer now however I was unable to use this in the default getDisplay since it requires the player and quest.
here the code note that I haven't cleaned it up yet so might look messy but it does the trick atm. [https://pastebin.com/JmPHfFXZ](https://pastebin.com/JmPHfFXZ)

**Comment by PikaMug** [comment]
After some thought, what I think would be preferable is the ability to set multiple count prompts. However, I'm not sure of how to best ensure a given count is associated with the desired string prompt. Maybe some sort of unique prompt ID? Unfortunately, I haven't the time to explore that further.

A quicker solution might be for you to offer multiple objective classes with the same purpose. Your pastebin expired, but let's say MyObjective1, MyObjective2, etc. which all have the same purpose but would of course have their own counts. I realize it's not the prettiest on your end, but it should work without issue on the current release. If a single class is truly necessary, working in your own I/O is the alternative.

**Pull request closed without merging**
