### PR TITLE
When a block is placed, deduct from the Blocks Broken objective

### PR DESCRIPTION
**Pull request by therbz**
Aims to resolve [Issue 1951](https://github.com/PikaMug/Quests/issues/1951).

All I did was copy the code from the onBlockBreak listener and put it into the onBlockPlace listener, changing some references.
I've tested it and it seems to work but I still think further testing is required.

### CODE REVIEW

**Comment by PikaMug** [comment]
Thanks for the commit! If you have a SpigotMC username you'd like tagged in the patch notes there, comment it below.

**Comment by therbz** [comment]
> Thanks for the commit! If you have a SpigotMC username you'd like tagged in the patch notes there, comment it below.

No worries. My spigot page is [https://www.spigotmc.org/members/therbz.135993/](https://www.spigotmc.org/members/therbz.135993/)

I do have one question though about the code. In the onBlockBreak event, the code responsible for checking and deducting 1 from the counter is duplicated and I'm not sure why.
```
                        if (currentStage.containsObjective(placeType)) {
                            for (final ItemStack is : quester.getQuestData(quest).blocksPlaced) {
                                if (evt.getBlock().getType().equals(is.getType()) && is.getAmount() > 0) {
                                    ItemStack toPlace = new ItemStack(is.getType(), 64);
                                    for (final ItemStack stack : currentStage.getBlocksToPlace()) {
                                        if (ItemUtil.compareItems(is, stack, true) == 0) {
                                            toPlace = stack;
                                        }
                                    }

                                    final QuesterPreUpdateObjectiveEvent preEvent
                                            = new QuesterPreUpdateObjectiveEvent(quester, quest,
                                            new BukkitObjective(placeType, is.getAmount(), toPlace.getAmount()));
                                    plugin.getServer().getPluginManager().callEvent(preEvent);

                                    final int index = quester.getQuestData(quest).blocksPlaced.indexOf(is);
                                    final int newAmount = is.getAmount() - 1;
                                    is.setAmount(newAmount);
                                    quester.getQuestData(quest).blocksPlaced.set(index, is);

                                    final QuesterPostUpdateObjectiveEvent postEvent
                                            = new QuesterPostUpdateObjectiveEvent(quester, quest,
                                            new BukkitObjective(placeType, newAmount, toPlace.getAmount()));
                                    plugin.getServer().getPluginManager().callEvent(postEvent);
                                }
                            }
                        }
                        dispatchedPlaceQuestIDs.addAll(quester.dispatchMultiplayerEverything(quest, placeType,
                                (final IQuester q, final IQuest cq) -> {
                                    if (!dispatchedPlaceQuestIDs.contains(cq.getId())) {
                                        for (final ItemStack is : q.getQuestData(cq).blocksPlaced) {
                                            if (evt.getBlock().getType().equals(is.getType()) && is.getAmount() > 0) {
                                                ItemStack toPlace = new ItemStack(is.getType(), 64);
                                                for (final ItemStack stack : quester.getCurrentStage(cq).getBlocksToPlace()) {
                                                    if (ItemUtil.compareItems(is, stack, true) == 0) {
                                                        toPlace = stack;
                                                    }
                                                }

                                                final QuesterPreUpdateObjectiveEvent preEvent
                                                        = new QuesterPreUpdateObjectiveEvent((Quester) q, cq,
                                                        new BukkitObjective(placeType, is.getAmount(), toPlace.getAmount()));
                                                plugin.getServer().getPluginManager().callEvent(preEvent);

                                                final int index = q.getQuestData(cq).blocksPlaced.indexOf(is);
                                                final int newAmount = is.getAmount() - 1;
                                                is.setAmount(newAmount);
                                                q.getQuestData(cq).blocksPlaced.set(index, is);

                                                final QuesterPostUpdateObjectiveEvent postEvent
                                                        = new QuesterPostUpdateObjectiveEvent((Quester) q, cq,
                                                        new BukkitObjective(placeType, newAmount, toPlace.getAmount()));
                                                plugin.getServer().getPluginManager().callEvent(postEvent);
                                            }
                                        }
                                    }
                                    return null;
                                }));
```
The same for loop code is repeated, but the one after is wrapped around `dispatchedPlaceQuestIDs.addAll()`
I didn't include this second block of code in my PR, but it works so I'm not really sure what it does and I don't know if it needs to be added to my PR

**Comment by PikaMug** [comment]
That's for party integration. So the first loop is for the player breaking the block, the second loop takes care of their party members. It would be preferable, yes.

**Comment by therbz** [comment]
Ah okay that makes sense

**Pull request merged**
